---
# Source: localstack/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: localstack
  namespace: shared-developer-services
  labels:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
  annotations:
---
# Source: localstack/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: shared-developer-services
  name: localstack
  labels:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
# Source: localstack/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: localstack
  namespace: shared-developer-services
  labels:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: localstack
roleRef:
  kind: Role
  name: localstack
  apiGroup: rbac.authorization.k8s.io
---
# Source: localstack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: shared-developer-services
  labels:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
  annotations:
spec:
  ports:
    - name: edge
      protocol: TCP
      port: 4566
      targetPort: 4566
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
---
# Source: localstack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: shared-developer-services
  labels:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: localstack
      app.kubernetes.io/instance: localstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localstack
        app.kubernetes.io/instance: localstack
    spec:
      serviceAccountName: localstack
      securityContext: {}
      containers:
        - name: localstack
          securityContext: {}
          image: "localstack/localstack:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: edge
              containerPort: 4566
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /_localstack/health
              port: edge
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /_localstack/health
              port: edge
          resources: {}
          env:
            - name: DEBUG
              value: "0"
            - name: EXTERNAL_SERVICE_PORTS_START
              value: "4510"
            - name: EXTERNAL_SERVICE_PORTS_END
              value: "4560"
            - name: LOCALSTACK_K8S_SERVICE_NAME
              value: localstack
            - name: LOCALSTACK_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LAMBDA_RUNTIME_EXECUTOR
              value: "docker"
            - name: LAMBDA_K8S_IMAGE_PREFIX
              value: "localstack/lambda-"
            - name: LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT
              value: "60"
            - name: OVERRIDE_IN_DOCKER
              value: "1"
      volumes:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: localstack-anyuid-rb
  namespace: localstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: localstack
    namespace: localstack
